const express = require('express');
const UserController = require('../controllers/UserController');
const router = express.Router();
router.get('/users',UserController.index);
router.get('/',UserController.show);
router.post('/registerStep1',UserController.registerStep1);
router.post('/registerStep2',UserController.registerStep2);
router.post('/verify',UserController.verify);
router.post('/login',UserController.login);
router.post('/forgotPassword',UserController.forgotPassword);
// router.put('/',UserController.update);
// router.delete('/',UserController.delete);
module.exports = router;